#!/opt/homebrew/bin/python3

import sys, argparse, base64, openai
from PIL import Image
from io import BytesIO


# Set up argument parser
parser = argparse.ArgumentParser(description="Generate an image with OpenAI.")
parser.add_argument("prompt", help="Image prompt, e.g., 'A horse on the moon'")
parser.add_argument("-s", "--size", choices=["small", "medium", "large"], default="large", help="Image size: 'small' (256x256), 'medium' (512x512), or 'large' (1024x1024) (default: 'large')")

# Parse command line arguments
args = parser.parse_args()

# Check if prompt is provided
if not args.prompt:
   print('Please provide an image prompt, e.g., "A horse on the moon"')
   sys.exit(1)

# Map size arguments to actual dimensions
size_mapping = {
   "small": "256x256",
   "medium": "512x512",
   "large": "1024x1024"
}
SIZE = size_mapping[args.size]

# Generate image
response = openai.Image.create(
   response_format="b64_json",
   prompt=args.prompt,
   size=SIZE
)["data"][0]["b64_json"]

# Decode the Base64 image and open it as a .png file
photo = base64.b64decode(response)
Image.open(BytesIO(photo)).show()
